name: Test

on: [push, pull_request]

env:
  CI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: (cd functions && npx jest)

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i

      - name: Install cli tools
        run: npm i -g firebase-tools

      - name: Deploy firestore rules
        run: firebase deploy --only firestore

      - name: Deploy storage rules
        run: firebase deploy --only storage

      - name: Deploy firebase functions
        run: firebase deploy --only functions
