name: Test

on: [push, pull_request]

env:
  CI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: (cd functions && npx jest)

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i

      - name: Install cli tools
        run: |
          npm config set prefix ~/npm
          npm i -g firebase-tools tslint typescript

      - name: Deploy
        run: |
          export PATH="$PATH:$HOME/npm/bin"
          firebase deploy --only firestore
          firebase deploy --only storage
          firebase deploy --only functions
